# example:
# $ make bin/crypto_sign/falcon/falcon512/amd64/avx2/bench DEFINE='-DTIMINGS=500 -DMININBYTES=128 -DMAXINBYTES=128 -DRUNS=5 -DST_ON -DST_MAX=2 -DST_PER=1' RANDINC='../test/common/' RANDLIB='../test/common/notrandombytes.c'
# $ ./bin/crypto_sign/falcon/falcon512/amd64/avx2/bench - 

EXTERNAL_PATH    = $(subst $(BIN),external,$(@D))
EXTERNAL_LIB     = ../test/$(EXTERNAL_PATH)/$(subst -,_,$(subst /,_,$(EXTERNAL_PATH))).a
EXTERNAL_COMPILE = $(CC) $(CFLAGS) -o $@ $(DEFINE) $(DNAMESPACES) $(INCLUDES) $(MAIN) $(PRINT) $(ASM) $(RANDLIB) $(EXTERNAL_LIB) -lgsl $(CIL)
